# Generated by Django 3.1.2 on 2020-10-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anasayfa',
            new_name='AboutUs',
        ),
        migrations.RenameModel(
            old_name='avantajlar',
            new_name='Advantages',
        ),
        migrations.RenameModel(
            old_name='Hakkimizda',
            new_name='mainPage',
        ),
        migrations.RenameModel(
            old_name='Hizmetler',
            new_name='Services',
        ),
        migrations.RenameModel(
            old_name='NedenBiz',
            new_name='WhyUs',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Hakkımızda'},
        ),
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name_plural': 'Avantajlarımız'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name_plural': 'Anasayfa yazısı'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Hizmetlerimiz'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name_plural': 'Neden Biz?'},
        ),
    ]
