# Generated by Django 3.1.2 on 2020-10-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0002_auto_20201028_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name_plural': 'Sektorlar'},
        ),
    ]
