# Generated by Django 3.1.2 on 2020-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0003_auto_20201028_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200, verbose_name='Adres 1')),
                ('address2', models.CharField(max_length=200, verbose_name='Adres 2')),
                ('telephone', models.CharField(max_length=30, verbose_name='Fax')),
                ('fax', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=200, verbose_name='Eposta')),
            ],
            options={
                'verbose_name_plural': 'Iletisim',
            },
        ),
    ]
