# Generated by Django 3.1.2 on 2020-10-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='alt yazi'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fax)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='alt yazi'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='aciklama'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='hizmet adi'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='aciklama'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='reason',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='hizmet adi'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='reasonMavi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Mavi kelemeyle cumlenin basina opsiyonel olarak eklenecek'),
        ),
    ]
