# Generated by Django 3.1.2 on 2020-10-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0006_auto_20201028_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictures', to='s4in.projects', verbose_name='resimler')),
            ],
        ),
    ]
