# Generated by Django 3.1.2 on 2020-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4in', '0010_projects_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(null=True, verbose_name='Proje tarihi'),
        ),
    ]
